import { useState, useCallback, useMemo } from 'react';
import { Plus, RotateCcw, Save, Download, GraduationCap, LogOut } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { useNavigate } from 'react-router-dom';
import CourseRow from '@/components/CourseRow';
import GPAResult from '@/components/GPAResult';
import CGPACalculator from '@/components/CGPACalculator';
import GradeTable from '@/components/GradeTable';
import AcademicTips from '@/components/AcademicTips';
import SemesterHistory from '@/components/SemesterHistory';
import GPAChart from '@/components/GPAChart';
import ThemeToggle from '@/components/ThemeToggle';
import { Course, Semester, calculateGPA, createCourse, loadSemesters, saveSemesters } from '@/lib/gpa';

export default function Index() {
  const [courses, setCourses] = useState<Course[]>([createCourse(), createCourse(), createCourse()]);
  const [semesterName, setSemesterName] = useState('Semester 1');
  const [semesters, setSemesters] = useState<Semester[]>(loadSemesters);

  const { gpa, totalCredits, totalPoints } = useMemo(() => calculateGPA(courses), [courses]);

  const updateCourse = useCallback((id: string, updated: Course) => {
    setCourses(prev => prev.map(c => c.id === id ? updated : c));
  }, []);

  const removeCourse = useCallback((id: string) => {
    setCourses(prev => prev.filter(c => c.id !== id));
  }, []);

  const reset = () => {
    setCourses([createCourse(), createCourse(), createCourse()]);
    setSemesterName('Semester 1');
  };

  const saveSemester = () => {
    if (totalCredits === 0) return;
    const sem: Semester = {
      id: crypto.randomUUID(),
      name: semesterName,
      courses: [...courses],
      gpa,
      totalCredits,
      date: new Date().toLocaleDateString('en-ET', { month: 'short', year: 'numeric' }),
    };
    const updated = [...semesters, sem];
    setSemesters(updated);
    saveSemesters(updated);
    reset();
    setSemesterName(`Semester ${updated.length + 1}`);
  };

  const deleteSemester = (id: string) => {
    const updated = semesters.filter(s => s.id !== id);
    setSemesters(updated);
    saveSemesters(updated);
  };

  const exportPDF = () => {
    const content = `Ethiopian University GPA Report\n${'='.repeat(40)}\n${semesterName}\n\nCourses:\n${courses.map(c => `  ${c.name || 'Unnamed'} — ${c.credits} cr — ${c.grade}`).join('\n')}\n\nTotal Credits: ${totalCredits}\nTotal Grade Points: ${totalPoints.toFixed(1)}\nSemester GPA: ${gpa.toFixed(2)}\n\nGenerated by Ethiopian University GPA Calculator`;
    const blob = new Blob([content], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `GPA-Report-${semesterName.replace(/\s/g, '-')}.txt`;
    a.click();
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b bg-card/80 backdrop-blur-md">
        <div className="mx-auto max-w-6xl flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <GraduationCap className="h-5 w-5" />
            </div>
            <div>
              <h1 className="text-base font-bold leading-tight">Ethiopian University</h1>
              <p className="text-xs text-muted-foreground leading-tight">GPA Calculator</p>
            </div>
          </div>
          <ThemeToggle />
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-4 py-6 space-y-6">
        {/* Hero */}
        <div className="rounded-2xl p-6 sm:p-8 text-primary-foreground" style={{ background: 'var(--gradient-hero)' }}>
          <h2 className="text-2xl sm:text-3xl font-extrabold mb-2">Calculate Your GPA</h2>
          <p className="text-sm text-primary-foreground/70 max-w-lg">
            Designed for Ethiopian university students. Add your courses, select grades, and instantly see your semester GPA using the standard 4.0 scale.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Calculator */}
          <div className="lg:col-span-2 space-y-4">
            <div className="gpa-card p-5 space-y-4">
              <div className="flex items-center justify-between">
                <input
                  className="gpa-input max-w-[200px] font-semibold"
                  value={semesterName}
                  onChange={e => setSemesterName(e.target.value)}
                />
                <div className="flex gap-2">
                  <button onClick={reset} className="btn-outline text-xs px-3 py-1.5">
                    <RotateCcw className="h-3.5 w-3.5" /> Reset
                  </button>
                </div>
              </div>

              {/* Column headers */}
              <div className="grid grid-cols-12 gap-2 sm:gap-3 text-xs font-semibold text-muted-foreground px-1">
                <span className="col-span-1 text-center">#</span>
                <span className="col-span-4 sm:col-span-5">Course Name</span>
                <span className="col-span-2">Credits</span>
                <span className="col-span-3 sm:col-span-2">Grade</span>
                <span className="col-span-2 text-center">Action</span>
              </div>

              <div className="space-y-2">
                {courses.map((c, i) => (
                  <CourseRow
                    key={c.id}
                    course={c}
                    index={i}
                    onChange={updated => updateCourse(c.id, updated)}
                    onRemove={() => removeCourse(c.id)}
                  />
                ))}
              </div>

              <button onClick={() => setCourses(prev => [...prev, createCourse()])} className="btn-primary w-full">
                <Plus className="h-4 w-4" /> Add Course
              </button>
            </div>

            {/* GPA Result */}
            {totalCredits > 0 && <GPAResult gpa={gpa} totalCredits={totalCredits} totalPoints={totalPoints} />}

            {/* Action buttons */}
            {totalCredits > 0 && (
              <div className="flex flex-wrap gap-2">
                <button onClick={saveSemester} className="btn-primary flex-1">
                  <Save className="h-4 w-4" /> Save Semester
                </button>
                <button onClick={exportPDF} className="btn-outline flex-1">
                  <Download className="h-4 w-4" /> Export Report
                </button>
              </div>
            )}

            {/* CGPA */}
            <CGPACalculator currentGPA={gpa} currentCredits={totalCredits} />

            {/* History & Chart */}
            <GPAChart semesters={semesters} />
            <SemesterHistory semesters={semesters} onDelete={deleteSemester} />
          </div>

          {/* Sidebar */}
          <div className="space-y-4">
            <GradeTable />
            <AcademicTips />

            {/* Info section */}
            <div className="gpa-card p-5 space-y-2">
              <h3 className="font-bold text-sm">About Ethiopian GPA System</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Ethiopian universities including Addis Ababa University, Adama Science and Technology University, Jimma University, Hawassa University, and Mekelle University use the 4.0 GPA scale. Students need a minimum CGPA of 2.0 to graduate in most programs. The grading system ranges from A (4.0) for excellent performance to F (0.0) for failing grades.
              </p>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t mt-12 py-6 text-center text-xs text-muted-foreground">
        <p>Ethiopian University GPA Calculator · Built for students across Ethiopia 🇪🇹</p>
      </footer>
    </div>
  );
}
